version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "67:48:b0:b3:95:05:37:1a:87:92:93:bb:67:d2:d2:90"
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - run:
          name: Install Hexo CLI
          command: |
            sudo yarn global add hexo
      # - restore_cache:
      #     key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: yarn install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Remove deploy_git
          command: rm -rf .deploy_git
      - run:
          name: Generate blog
          command: hexo generate
      - run:
          name: Deploy
          command: |
              git config --global user.name "Circle CI"
              git config --global user.email "bot@circleci.com"
              hexo deploy
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - "1d:0c:ea:28:8a:4f:f0:5d:98:e1:ca:93:0f:38:d6:ab"
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "bot@circleci.com"
            hexo deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: hexo
